### ISSUE TITLE
Entities position wrong for hashtags

### ISSUE THREAD

**Issue by ralfr** [appdotnet/api-spec#131]
We are experiencing crashes in AppApp due to an issue with ADNs hashtag detection. For example the following post

```
RP @eay: Think about this: Twitter wasn't able to create something like Smart Push Notification in three years (since Apple introduced the Push Notification Service), while @ralf, @sneakyness & Co. did it in 10 days! #AppApp
```

gets a hashtag identifier for position 219 with a length of 7. The hashtag starts at 218. Which causes an index out of boundaries error when parsing. Can you look into this. Doesn't happen with every post. Just sporadically.

**Comment by tonymillion** [comment]
Yep seeing the same thing in xtendr (though I adjusted the range) there is also a problem with range (sometimes) when the post begins with an emoji 

see: http://i.imgur.com/LW4rW.jpg

**Comment by ralfr** [comment]
For @berg and @mxml-barmstrong @mthurman to further investigate, it happens on post id: 

`170655` 

which seems to contain invalid invisible characters:

```
&#55357;&#56891; RP @eay: Think about this: Twitter wasn&apos;t able to create something like Smart Push Notification in three years (since Apple introduced the Push Notification Service), while @ralf, @sneakyness &amp; Co. did it in 10 days! #AppApp
```

The hashtag entities dictionary contains the wrong start position, hence causing an index out of boundaries issue.

**Comment by richardofsussex** [comment]
If you're getting character-counting issues, does this suggest that the underlying character encoding isn't solidly engineered?  Is the intention to work natively with UTF-8 [1], and if so is there code to ensure that that's what you're starting with, when processing a post?  (Also, in UTF-8, "character" and "byte" are not the same thing.)

Richard

[1] http://www.ietf.org/rfc/rfc4627.txt

**Comment by ralfr** [comment]
I'm not an App.net developer, just a third party developer. All I'm saying is that

https://alpha-api.app.net/stream/0/posts/170655?access_token=<INSERT TOKEN HERE>

returns a post with trailing `\ud83d\ude3b` characters and that the hashtag entity range of 7,219 causes issues when trying to pass to NSAttributedStrings in Objective-C.

**Comment by berg** [comment]
Actually, this is specific to Objective-C. When NSString talks about "characters," what it really means is "UTF-16 code points." Because emoji are outside the range of characters that can be expressed by a single UTF-16 code point, they are encoded as a surrogate pair — in your case, `\ud83d\ude3b`. The server portion of App.net is written in Python, which counts these as a single character (in closer compliance with the spec, IMHO.)

It's complicated a bit by the fact that JSON uses Javascript character encoding — which has a similar limitation to Objective-C (with slight, frustrating differences, naturally.) So in the JSON output, these emoji characters are encoded as a surrogate pair. But they still represent a single character.

You may wish to refer to this blog post for a bit more information about how this works specifically in Objective-C: http://boredzo.org/blog/archives/2012-06-03/characters-in-nsstring

and this

http://stackoverflow.com/questions/10044196/apple-emoji-iterate-through-nsstring

Hope that's helpful, thanks!
