### ISSUE TITLE
Can stream/0/token also return the app that created the token?

### ISSUE THREAD

**Issue by tonymillion** [appdotnet/api-spec#134]
It would be handy for a webapi to know the token it has just been passed came from itself, and that someone isn't trying to fake things with a token from another app.

Facebook use this to secure access to the API, and I think its a worthwhile addition.

**Comment by mthurman** [comment]
Access tokens are meant to be passed from an application directly to the App.net API, not through another web api. Since access tokens are supposed to be secret and not shared, only the app that requested that token should have a copy of it. Thus, I don't think this information needs to be exposed in the token endpoint. It might be useful in a debug tool like Facebook has (https://developers.facebook.com/tools/debug) but I don't think it makes sense at the API level.

Could you explain you use case a little bit more and what Facebook is doing that would be helpful?

**Comment by tonymillion** [comment]
Ok.

In my case I have a push notification server running that needs to poll the user/mentions api end point (and eventually stream) on behalf of the user. 

The token was originally obtained from my iPhone app, then passed to my own push service web api so it can start the polling system for that user.

What I do is call stream/0/token on what I was given and use the information thats returned from _that_ call instead of anything the client tells me because it could all be lies/hackers.

I'd like to confirm the token I've been given was in fact generated for my app, and not for someone else's app who has then pushed their token into my service.

Imagine this case (for facebook): 
I release an iOS app, it logs in via facebook and gives me the access_token so I can query facebook and get the users details to create an account (all fairly standard). 

Because of often lax security in many places, using the Facebook token that I have in my data base for "Mr Joe Bloggs" I can use to log in to Pinterest as "Joe Bloggs" where I get a new pinterest access_token. 

If Pinterest had actually confirmed that the token I gave them came from Pinterest and not TonyApp then they could have rejected the login.

**Comment by tonymillion** [comment]
In addition it doesn't have to be much, just the app name would be enough (and/or the app ID)

**Comment by mthurman** [comment]
Ok, I see the use case right now, but I'm hesitant to solve this problem this way because:

1) it seems like that's mostly and authentication problem between your ios app and the push notification server you're running

2) subscriptions will be the recommended way of doing push notifications in the future and those require an app access token so you shouldn't need to share the user token in the future.

That being said, I'm not sure if there's a downside to making this information available through the api so it may happen.

**Comment by dquick-freelance** [comment]
Would have to be client_id - app name is currently non-unique

**Comment by tonymillion** [comment]
Right now, its the _only_ way to do it, as my server server has to poll on behalf of the user who logged in to the iOS client. Unless I kick the user out of the client to approve _another_ app.net app there is no other way to do it.

Keep in mind, none of this stuff "existed" for app.net, push notifications are a fairly well known thing, but the comms between adn and getting a push to a device hasn't really been done before. I'm pretty sure the appapp guys solved this exactly the same way I have, by pushing the client access_token from the device up to a private server so it can poll on behalf of the user.

Push notifications are ridiculously useful for people (and a lot of people are using my app now) so making that flow as simple as possible for them is very important.

Maybe there should be an client->app access token escalation?

**Comment by tonymillion** [comment]
@dquick-freelance yes, that would be fine as long as its something I know to be able to confirm a client token came from the right place.

**Comment by berg** [comment]
Digging through looking for something else, I just found this issue. We'll get this shipped this week if it hasn't been done yet. I understand why this is useful and necessary for security. I think all you should need is to be able to retrieve the client_id that created the access token, right?

**Comment by tonymillion** [comment]
Yep that would work perfectly.

**Comment by mthurman** [comment]
We just rolled out code that adds this behavior.
