### ISSUE TITLE
Way of syncing 'read position' between clients

### ISSUE THREAD

**Issue by amyworrall** [appdotnet/api-spec#139]
For each of the user's stream, their @mentions, and for the direct messages stream and for each list (when/if those features appear), the system should provide a "position" field in the API. The field should contain a post ID, a last updated time, and a client ID (of who did the last update).

This should be gettable and settable by clients. When setting the field, the client should have to pass in the previous value for the last post ID, as well as the new value. If the previous value doesn't match up with what was currently in the field, the API could reject the update — I'm thinking of the use case where user uses Client 1 and sets a position. Then user uses Client 2, somehow it doesn't manage to read the position properly and just starts the user at the top of the feed, but then it tries to set the position to the top when the user switches tab. This is suboptimal since the user has now lost their position. I'm not sure quite what algorithm should be used here, but we could take a look at what TweetBot does, since they tend to get it right :)

Position should be streamed if there's API streaming support: if the user scrolls one client, and it sends the position to the server, other clients should scroll to that position too, as if it's one single view that just happens to be on multiple devices.

**Comment by thingsinjars** [comment]
I'm thinking this could be handled with a textless post. Your current position could be sent as a message from your account with no text content but with the additional meta data 'lastposition : 12345'. Any client that supported the lastposition meta just needs to access your stream for the most recent lastposition post and adjust accordingly. No need for additional work on the API side.

**Comment by mthurman** [comment]
We've definitely thought about this some and while nothing is currently implemented, in the spec we have something called 'app_data' that we envision for this kind of data: https://github.com/appdotnet/api-spec/blob/master/objects.md#user-fields

**Comment by thingsinjars** [comment]
@mthurman That would definitely work for this scenario but have there been any more advances on the textless post support? All the other discussions around that here seem to have evolved into very big-picture access control discussions where a 'headless' post concept could be reused simply for issues like this one here and others not covered in the user-fields docs.

**Comment by tonymillion** [comment]
@mthurman on the subject of app_data how are you going to handle the inevitable conflict-resultion that will be required in that dictionary?

**Comment by terhechte** [comment]
@mthurman I'd expect that users would also want the current read marker to work when they're in alpha, not just in client a, or b. Wouldn't it then be better to have a official standardized API for this instead of different clients writing this in different kind of ways into the app data? Or is the a users' app data shared, so that client a can read what client b wrote into the field?

**Comment by manton** [comment]
@thingsinjars Textless posts might introduce other problems. All clients would have to ignore these, and it'd make simple things like calculating the number of posts suddenly difficult. When I look at my server data for Tweet Marker, many users have set their marked position thousands of times. That would be thousands of these empty posts, in some cases dwarfing real posts.

@mthurman Is app_data actually implemented yet? I didn't see anything in the API spec for POSTing a changed user.

If app_data was used, I think it would need:
- Some basic convention for how to label this data. Clearly you don't want your app name in this, as the example JSON shows, because this is data that needs to be shared between applications. (Apps could have private sync data, but the basic position for timeline and mentions should be available to everyone.)
- A way to set only app_data without requiring all the other user data (name, avatar, etc).

If it helps, I'd suggest checking out the Tweet Marker API (linked in that issue above that opened and closed before seeing this in GitHub). There are a couple things it does that make dealing with conflicts easier, like timestamps and a version number that increments automatically on the server. https://github.com/manton/tweetmarker/blob/master/documentation/v2.md

It's not perfect but there are a bunch of clients that have been doing this on the Twitter side for a year and they've learned a lot. The biggest room for improvement is faster sync, which a streaming API would solve.

**Comment by thingsinjars** [comment]
@manton This is true but introducing the textless option sooner rather than later means fewer clients would need to cater for the change. 

With textless posts, the platform becomes a generic streaming solution which can be used for a wider variety of technologies. Having text mandatory means either requiring multiple accounts per user (one for conversation to be followed, one as a meta-data back channel) or limiting posts to be meta-data enhanced conversations. The latter isn't a bad thing but it’s a subset of the potential use cases for the platform.

**Comment by orianmarx** [comment]
We've implemented this as Stream Markers http://developers.app.net/docs/resources/stream-marker/

I'm closing this thread but new threads are welcome to help us improve Stream Markers.
