### ISSUE TITLE
Including reposters doesn't seem to work

### ISSUE THREAD

**Issue by terhechte** [appdotnet/api-spec#190]
Hey, I just tried to add 'include_reposters_=1' to a request. When I include it like that, I don't get any results (i.e. there's no reposters entry in the results). When I include 'include_reposters=1' (I thought that the last underscore was maybe a typo) then I get an error 500 from the server.
Could it be that including reposters doesn't work right now?

**Comment by terhechte** [comment]
Also, it seems that reposted posts don't contain the original annotations if I'm not wrong. I just reposted post 421380 by tonymillion, and the annotations field in the repost (id 421395)  is empty. Now I could technically access the annotations through the "repost_of" field, but I'm not sure whether that's expected behaviour?

**Comment by mthurman** [comment]
1) it should be `include_reposters=1`. Are the docs missing that _ somewhere?
2) you found a bug--a fix should be going out shortly
3) The repost will not have annotations and that is expected behavior. Reposts are meant to be pointers to the original post. They have a text/html/entities so we can return something to clients who don't support the `repost_of` field yet. But in general, most clients will want to interact with `post.repost_of` when they are rendering things, pulling out annotations, replying, etc. There's no benefit in duplicating what might be an 8k blob in both the `post.annotations` and `post.repost_of.annotations`

I'll come back and close this once the fix has been rolled out.

**Comment by terhechte** [comment]
Regarding 1) The docs state that it is `include_reposters_=1` markdown caused the wrong display above. 
2) Thanks, that's great! Will add it soon
3) Ok, good to know. I'll just map to post.repost_of then. I was confused because the docs state that "a repost's text, annotations, etc. are inherited from the original Post.". Since the text property was obviously available, I wondered why annotations weren't there. 

Thanks!

**Comment by mthurman** [comment]
Ok, I pushed some docs to try to clarify what is inherited https://github.com/appdotnet/api-spec/blob/master/resources/posts.md#repost-a-post

**Comment by mthurman** [comment]
Ok, this fix is pushed.
