### ISSUE TITLE
Is this okay to do?

### ISSUE THREAD

**Issue by scruffyfox** [appdotnet/api-spec#197]
Im contemplating the idea of creating a custom push notification service on my server for the app im working on, and really the only thing I can think of I can do is to create a service which periodically checks the user's mentions for any new.

Now the issue is, you would need an access token in order to do this. Would it be wrong to (obviously when the user agrees to in the app) send and store their access token (encrypted) onto my server which is then used to check the api for new mentions?

Or I could even use my own auth token to do this?

Thoughts/suggestions? 

Like I said, Just a thought, obviously wouldn't implement it if it's a massive no-no.

**Comment by berg** [comment]
Is the server associated with the app — i.e., are you running both?

If so, yeah, this is totally kosher — for your own safety, I suggest that you call to the /stream/0/token endpoint from the server and ensure that the client_id in the reply matches your own; that way an unscrupulous developer can't use an access token _they_ might have for another user to talk to your service.

What some other folks have done so far is poll the global stream as a single user (dedicated to the app, or their own account) and watch for mentions of any user who is using the app, then notify the appropriate parties.

We'll have subscriptions available soon where we can push these mentions to you, instead of you having to poll us for them.

**Comment by scruffyfox** [comment]
Yeah, it's all part of my app http://getrob.in

I was thinking of doing it server side + push notifications because our server has the luxury of doing cron jobs every x seconds where I wouldn't like to do that on the user's phone for obvious battery and performance reasons

Thanks

**Comment by berg** [comment]
Ah, cool, sounds good! Let me know if I can help at all.

**Comment by tonymillion** [comment]
Just to chime in, polling the users mention stream is "ok" but you'll rapidly kill your box or the time between users getting mention notifications will increase as user numbers of your app increase (I've tried this way for Rivr early on).

I very quickly transitioned to a stand alone service that polls global once every few seconds (as @berg has already suggested) looking for new mentions then looks up the userid from the mention in a database to see if that userid is hooked up to the app. 

Its written in python and doesn't even register any real system load while doing it.

The nice thing is with non-authed requests now polling global doesn't even require an access token any more. I _strongly_ suggest you do this now, rather than try to re-engineer after your app is released.

**Comment by scruffyfox** [comment]
Well I plan on releasing within the next couple months so hopefully before then ADN will release the subscription module and I can integrate that rather than the polling.

**Comment by tonymillion** [comment]
Ah yeah, if you're that far out then I'm sure subscriptions will be online by then.

Just thought I'd share my experience being one of the early pioneers ;)

**Comment by scruffyfox** [comment]
Appreciate it :D

**Comment by kosso** [comment]
I do this, but only every 20 seconds for now, while the global is manageable in his way,

Also storing the global steam to provide some interesting searches and slices of data which could be relevant or fun for the user of my app

**Comment by scruffyfox** [comment]
I only check the user's mention every minute anyway, I have a cron job that executes a task which goes through every user and updates the last mention id + sends a notification if the former count > 0

**Comment by tonymillion** [comment]
Just wait till you hit a few hundred users, your cron job will start overlapping itself.

**Comment by scruffyfox** [comment]
By then, the guys should have released subscriptions. I could just write a script that restarts the check after it finishes going through each user

**Comment by kosso** [comment]
exactly.
having one process per user is crazy talkin'!

Slurp the Global. It has everything you need.
