### ISSUE TITLE
Unable to perform hashtag search with non-ASCII characters

### ISSUE THREAD

**Issue by paulyhedral** [appdotnet/api-spec#210]
If I try to perform a hashtag search using non-ASCII characters, I get a 404:

$ curl https://alpha-api.app.net/stream/0/posts/tag/
{
    "error": {
        "code": 404,
        "message": "Not found"
    }
}

If I attempt to %-encode the characters, it's still a 404:

$ curl https://alpha-api.app.net/stream/0/posts/tag/%F0%9F%98%98
{
    "error": {
        "code": 404,
        "message": "Not found"
    }
}

**Comment by mthurman** [comment]
# right now isn't a valid hashtag since it's not a letter or digit. Valid unicode hashtags do work with this endpoint i.e.: https://alpha-api.app.net/stream/0/posts/tag/พล (this example does show that we've got some issues with some international alphabets, but I don't expect  will ever be a valid hashtag since it's a symbol)
