### ISSUE TITLE
PNG avatar image with transparency show @ symbol in the navbar

### ISSUE THREAD

**Issue by waliddamouny** [appdotnet/api-spec#216]
I uploaded an avatar PNG image with transparency which works fine for regular posts but shows the **@** symbol behind the avatar image in the navbar.

**Comment by voidfiles** [comment]
We just rolled out a fix for this.

**Comment by ghost** [comment]
@voidfiles Is the fix the black background I see? I don't think that is a very good fix. There should be an API so that when a transparent avatar is uploaded, the client (or the ADN web app) could offer to auto-select a background color or let the user chose one. I would prefer the auto-select option. Thoughts?

**Comment by waliddamouny** [comment]
@BreadAndButter I seem to see the transparency as it should be showing. If you are sure your file has transparency then it probably is a side effect of the saved PNG format. You can try saving the image without a colour for the transparent pixels. This is probably how I saved the PNG avatar image.
