### ISSUE TITLE
HashTags are Case InSensiTive

### ISSUE THREAD

**Issue by edent** [appdotnet/api-spec#225]
When Hashtags are stored in entities, they are shifted to lowercase.

That means `#HasHtAg` becomes `hashtag`

I appreciate that someone using `#Obama` is equally interested in `#obama` and `#OBAMA`.

But why store the entity in lower case only?

**Comment by mthurman** [comment]
Because that's it's "id" essentially. If we're saying that #obama == #Obama (which we are), then there needs to be some way to do that comparison. We chose to lowercase the tag that way things like filters work as expected. Note that we don't alter the "text" attribute so you should be able to display them and preserve the original case.
