### ISSUE TITLE
Include Latest Message within each Channel

### ISSUE THREAD

**Issue by swhitley** [appdotnet/api-spec#253]
When retrieving subscriptions, Omega displays the latest message for each channel.  This is a good pattern, but in many applications, the additional roundtrips will be expensive.  It would be convenient if the latest message was already included within each channel object.

Endpoint:  https://alpha-api.app.net/stream/0/channels

**Comment by tigerbears** [comment]
Seconded, particularly as the number of subscribed channels increases.

**Comment by paulyhedral** [comment]
+1

**Comment by ludolphus** [comment]
There is a new api that might help, it will still require one extra api call: http://developers.app.net/docs/resources/message/lookup/#retrieve-multiple-messages
This endpoint allows you to get multiple messages in one go, without specifying channels. It's not optimal because you'll have to match that result against the channel result...

So an option like 'include_latestmessage' would be more convenient, +1 to that.

**Comment by swhitley** [comment]
The new 'lookup' endpoint helps.  Thanks!  

It's still not optimal -- if I'm the owner of the channel and the latest message came from me, I'll still need to perform a lookup for other writers.

Incidentally, I don't know what best practices are, but I'm doing a lookup for the first five (5) writers and displaying names and avatars to show who is involved in the channel.  I'd love to hear how other people are approaching it. 

I'd also love to see a _filter_by_type_ option for all of these endpoints.  Potentially, you'd want to enumerate channels that are not on the first page of subscriptions.  You may not know the channel ids.

**Comment by berg** [comment]
Our plan is to encourage use of the mass-fetch endpoints in order to handle these cases. Hopefully you're keeping a local cache of message/channel/user objects, so you can grab the channels list, fetch any message you don't have a cached copy of, then fetch any user you don't have a cached version of (make sure you commit any user you learned about in the previous API call to cache first!)

We'll probably add a bit more functionality to the channel endpoint, but I'd really like to avoid including extra objects whenever possible.
