### ISSUE TITLE
post deletions via subscription

### ISSUE THREAD

**Issue by coyled** [appdotnet/api-spec#32]
Hi.  Are there any plans to make post deletion events available via subscription?

**Comment by nanek** [comment]
This is pretty much the same issue I posted, so I'm closing my ticket and posting it here.

I currently index the global stream to provide the search at http://appnet.herokuapp.com/search
I need a way to determine which posts have been deleted, so that I can remove them from the index.

Is there an existing API endpoint that I can poll to get a list of the deleted post ids? If not, can some sort of API, RSS feed, or notification mechanism be implemented so that I, and presumably other similar services, can handle deleted posts properly?

**Comment by mthurman** [comment]
This is available in the Streaming API: http://developers.app.net/docs/resources/stream/#post
