### ISSUE TITLE
Filter posts by language

### ISSUE THREAD

**Issue by janodev** [appdotnet/api-spec#36]
The ability to tag posts by language lets you discard posts in languages you don't understand, and post in your non-English language without pestering foreign followers. I guess this requires a language field in the post object.

**Comment by markwilcox** [comment]
Language could just be one of the globally defined annotations?

**Comment by janodev** [comment]
Indeed. It all comes down to define a `wellknown:language` annotation. I don't know the performance implications of adding annotations on Filter objects, but at least you can delegate the "filtering by annotation" to native clients, which is what most people use anyway.

**Comment by mattflaschen** [comment]
The annotation should probably use the ISO 639-2 three-letter codes for standardization.

**Comment by waliddamouny** [comment]
Many people around the globe post using the English alphabet a phonetic representation of the words of their native languages. Some others post using more than one language because many internet users whose mother tongue is not English are bilingual.

The point I'm trying to make is that language annotations should be optional and allow multiple language annotations. It should also specify if the post is phonetically dictated with the alphabet used and the language intended.

**Comment by orianmarx** [comment]
Our current Filter / Stream combo along with Annotations would enable this to be done. The question is getting developers to adopt it.

**Comment by mattflaschen** [comment]
There is now a core annotation, [net.app.core.language](http://developers.app.net/docs/meta/annotations/#language).
