### ISSUE TITLE
Need an api to check mutual following statuses between two users

### ISSUE THREAD

**Issue by prasadrl** [appdotnet/api-spec#48]
Also, allow username to be passed in as the input parameters.

**Comment by prasadrl** [comment]
Also, when returning the user object, you could return the mutual following status between the authenticated user and the user being fetched, as booleans. 

```
{ 
       ...
       follow_status
       { 
              follows : 1
              followed_by : 0
       }
}
```

**Comment by domness** [comment]
+1 on this, I don't want to be crawling through the followers/following list!

**Comment by ghost** [comment]
I came here to ask this too.

**Comment by kosso** [comment]
Currently every User Object (and the Post.user data) has this info now. 

is_follower and is_following - with respect to the authenticated user.

**Comment by domness** [comment]
Yeh this is all fine now. Can someone close this issue?

**Comment by ghost** [comment]
ahhh thanks

**Comment by mthurman** [comment]
Just to follow up, we've renamed `is_follower` and `is_following` since we thought they were a little confusing (who is following who?).  We now have `follows_you` and `you_follow` (https://github.com/appdotnet/api-spec/blob/master/objects.md#user-fields) which should make it really easy to determine follow relationships between the current user and another user.

**Comment by ghost** [comment]
Makes more sends to me. It is more clear.
