### ISSUE TITLE
Limitations of Annotations?

### ISSUE THREAD

**Issue by simondlr** [appdotnet/api-spec#5]
When Twitter launched annotations, I really digged the idea.

What are the expected limitations of this? Will there a be limit on how much annotations a post will have?

Considering that this will create a new set of keywords that developers might have to decide on, will app.net help in establishing standards? Or should developers establish standards themselves? In other words, say I want to add an annotation of a song, I might use something like "song", as opposed to my own site's tag "tweeklyfm:song" for standard's sake. Perhaps another way around this, is allow "vendor" annotations, but then also allow the addition of a "tag" field in the annotation. ie, with the rdio example:

```
"annotations": {
    "rdio:song": {
        "tag":"music",
        ...
    }
}
```

I think one of the great benefits of annotations will be the extraction of metadata from posts. ie, you can fetch all the songs with music information in it. Or all the posts with news annotations? It would be great if there is an endpoint that allows developers to retrieve posts by searching annotations. It seems you don't have a search endpoint yet, but it can be included in that by specifying it in the query parameters?

**Comment by berg** [comment]
I'll try to post some more about my thoughts on annotations taxonomy soon. In a nutshell, though, the idea is that there would be several well-known annotation types, but any developer would be able to define their own annotations, namespaced by their username.

My thinking is that we'll give you a pretty serious amount of leeway in terms of how much data we allow you to associate with a post—they're not meant to be shortcuts to more information, they're meant to encapsulate all of the metadata without further network fetches.

**Comment by simondlr** [comment]
Congratulations on the funding. I'm looking at annotations and filters. I assume, we will be able to filter a stream based on annotation data as well?

ie show only posts that has the tag "wellknown:geo" in it?

**Comment by stereoket** [comment]
Thanks for the feedback, may I suggest that an annotation document is created so that we can brainstorm ideas on suggested annotations and suggested formats. Very much like micro formats review proposals - I know I am most likely to use annotations to manage my in-app tagging system. It would be great to see microformats and that style of structured representation of data structures employed in and, such as events hcal, hcard etc geo tagging is common, and would be great to use commonly agreed syntax.

**Comment by alinford** [comment]
+1 on this idea. Applications being able to embed data in the comms flow allow for interesting applications. What about annotations in the user profile? 

Consequently, in terms of auth, how about being able to register custom scope so that users can authorise application data settings access? So if i have some user annotations. So i could have a custom type 'rdio' in the example above.. if i was writing a mashup between my service and rdio, i could request access to this (and if it wasn't available, i could instruct the user that my service only works with rdio users on app.net). thoughts?

**Comment by stereoket** [comment]
i'm hoping well known annotations include:

geo:
point (lat/long)
place (polygon array of lat long points)

rehsare/repost count (in array)
although this may link to other issues, a reshare of a post could contain the originiating userID in an array - for apps to then thread back to the the users who shared the post.

post_type (this could be global top-level taxonomy of sorts) eg. Video/Photo/Link/

a custom_scope could be interesting, but you could manage that via your auth callback and store that on your own system, i think, and then use custom annotations perhaps.

(i'm @ketan on ADN btw)

**Comment by kosso** [comment]
MIME type

**Comment by tonymillion** [comment]
What exactly should an annotation look like in the create post call? can we have a sample JSON encoded string, cos I'm having trouble getting the API to accept mine.

**Comment by simondlr** [comment]
Tried it myself too and got 500 (HTML) errors. Asked @berg about it. He suspected it isn't working right: https://alpha.app.net/berg/post/45683

**Comment by tonymillion** [comment]
Ah well that is a disappointment :( 

I had big plans for cool stuff today, I guess I better go and sit in the park

**Comment by mthurman** [comment]
Yeah just to be clear, annotations are not live yet. Due to all the discussion that's been happening, we probably need to go back to the drawing board and integrate some feedback. The past 2 weeks have been kinda hectic but this is really high on our list once some more fires are put out. (It's what we're really excited about too).

**Comment by tonymillion** [comment]
In a nutshell whats the feedback you're going to integrate? To me the concept of annotations seems perfectly clear - App makes post, App can add "additional data" to post to enhance it. 

I realise that could end up with 15 different ways of having geolocation tagged in a post, but if you want to formalise that then make it a "proper" member of the post object. (In the geo case you'd need to be able to build indexes on the geo data anyway).

My 2c put annotations in as a app defined area for non-text (i.e. app specific) storage and do all the fruity stuff separately.

**Comment by orianmarx** [comment]
Closing this as we've rolled out Annotations and they are documented here: http://developers.app.net/docs/meta/annotations/
