### ISSUE TITLE
app_data permissions

### ISSUE THREAD

**Issue by pbnjay** [appdotnet/api-spec#51]
Would be nice to have (fine-grained) permissions for app_data (default from the app developer, modifiable by the user).

For the Rdio example mentioned in the specs, assume that more than just the song id is annotated by the Rdio app.  Embedding the rdio song id publicly makes sense. But, you might not want the world to know that the song was on your "gettin groovy" playlist, so you'd make that component private.

Another example would be some type of weight loss app. You could share your percentage progress publicly, but for better accountability, you'd share the actual gain/loss in lbs with your support group.

I could easily seen this implemented as a dictionary of app_data keys mapping to groups/user id lists.

**Comment by ryanschneider** [comment]
I could see a similar use-case for turn-based asynchronous games built on app.net.  A user could post that they completed their turn and mention or otherwise annotate the post so an adjudicator could find it.  The adjudicator would have access to a private field that contains the actual move data (for games not played fully in the open, e.g. Poker or Diplomacy).

**Comment by orianmarx** [comment]
We're no longer pursuing the app_data concept but may be replacing it with something else. In the meantime, I'm closing this thread.
