### ISSUE TITLE
Please rename this whole thing

### ISSUE THREAD

**Issue by CocoaPriest** [appdotnet/api-spec#56]
app.net (AppDotNet?) is a horrible name. And it can't be used as a verb anyway

**Comment by ralfr** [comment]
Very likely a discussion to be held on App.net itself, versus here on GitHub. Sorry to say but really not an API issue at all...

**Comment by jeremyheiler** [comment]
Some people like the fact that it cannot be expressed as a verb.

**Comment by sneakyness** [comment]
Some people like to turn it into a verb anyways. "I totally just app dot netted that"

**Comment by shawnhooper** [comment]
The only verbs that should be discussed here are GET, POST, PUT and DELETE, etc. :)

**Comment by wedtm** [comment]
and OPTIONS, don't forget OPTIONS.

**Comment by abraham** [comment]
We should get some PATCH in here too!

**Comment by pocketWashburn** [comment]
since when do API's/infrastructure names need to be verbs?  App.net is supposed to be infrastructure that allows other services to do their thing.  Let those services come up with verbs if need be, although 'post' works just fine?  just because twitter has tweet doesn't mean App.net needs something.  Additionally if the service's name was an easy verb it would distract from the third party platforms using the service, which is why App.net is perfect, its generic, its the underlying service.  Even the reference implementation currently being used isn't 'App.net' its 'Alpha'.

**Comment by tgvashworth** [comment]
@pocketWashburn has it right. App.net is the API/platform layer. The _app_ is the important thing. App.net should be almost invisible.
