### ISSUE TITLE
Entity link objects should include displayable version

### ISSUE THREAD

**Issue by johnsheehan** [appdotnet/api-spec#9]
https://github.com/appdotnet/api-spec/blob/master/objects.md#links

Something like a subset of the total URL (e.g. remove http(s):// and limit length). This is the version that should be used in the pre-processed text_html mentioned in #8

**Comment by berg** [comment]
I was going to avoid doing this, because the idea is that we want to allow arbitrary anchor text for links. We can autogenerate an abbreviated version for bare URLs included in posts. Does this satisfy your request, or do you still have an application for displayable links that are not bare URLs?

We probably _will_ include, at least, a displayable host ala HN.

Also, we do not plan to auto-shorten links.

**Comment by johnsheehan** [comment]
I was thinking of this use case: http://screencast.com/t/5feEz6lp4u (just enough of the link is displayed to be useful without breaking the display)

**Comment by berg** [comment]
Yes, that's what I'm talking about when I say "bare URLs" — but additionally we want to be able to allow you to specify your own anchor text, if you like.

**Comment by orianmarx** [comment]
Closing this as we now support link entities with custom anchor text: http://developers.app.net/docs/meta/entities/#links-with-custom-anchor-text
